kind: Secret
apiVersion: v1
metadata:
  name: backstage-postgresql
  labels:
    app.kubernetes.io/instance: backstage
    app.kubernetes.io/name: backstage-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  postgres-password: {{ .Values.postgresql.databasePassword }}
type: Opaque