apiVersion: v1
kind: Secret
metadata:
  name: developer-hub-postgresql
  labels:
    {{- include "rhdh.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseName: "{{ .Values.postgresql.databaseName }}"
  databaseUser: "{{ .Values.postgresql.databaseUser }}"
  databaseAdminPassword: "{{ .Values.postgresql.databaseAdminPassword }}"
  databasePort: "{{ .Values.postgresql.databasePort }}"
{{- if .Values.postgresql.databaseHost }}
  databaseHost: "{{ .Values.postgresql.databaseHost }}"
{{- else }}
  databaseHost: "{{ include "rhdh.postgresql.name" . }}"
{{- end }}



  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
