kind: Secret
apiVersion: v1
metadata:
  name: mad-developer-hub-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  .dockerconfigjson: {{ .Values.pullSecret }}
type: kubernetes.io/dockerconfigjson